/run/numberOfThreads 4

#/IonTrack/det/setFilmXY 1 um
#/IonTrack/det/setFilmZ  1 um

#/IonTrack/stepMax 10 nm

#/IonTrack/phys/addPhysics dna_opt2
#/IonTrack/phys/addPhysics dna_sta_opt2 # there is no sta-type list on cluster

#/process/em/pixe true
#/process/em/fluo true
#/process/em/auger true
#/process/em/augerCascade true
#/process/em/deexcitationIgnoreCut true

# verbose
#/control/verbose 2
#/run/verbose 2
#/tracking/verbose 2
