/control/execute ./init.mac

# define scoring mesh
/score/create/boxMesh boxMesh
/score/mesh/boxSize 50 50 50 nm
/score/mesh/nBin 50 50 1
/score/quantity/energyDeposit eDep eV
/score/close
/score/list

#/IonTrack/gun/distance 0 nm
/gun/particle ion
/gun/ion 14 28 
/gun/energy 25 MeV
/gun/position 1 0 0 nm

/run/printProgress 10
/run/beamOn 1000

# Dump scorers to a file
/score/dumpQuantityToFile boxMesh eDep edep.dat
