/control/execute ../init.mac

/IonTrack/det/setFilmXY 120 nm
/IonTrack/det/setFilmZ  150 nm

/run/initialize

#################################################
/vis/open OGL
/vis/viewer/set/autoRefresh false
/vis/verbose errors

/vis/drawVolume
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/scene/endOfEventAction accumulate
/vis/scene/add/axes

/vis/viewer/set/autoRefresh true
/vis/verbose warnings
